require("nyto.plugins-setup")
require("nyto.core.colorscheme")
require("nyto.core.keymaps")
require("nyto.core.options")

require("nyto.plugins.comment")
require("nyto.plugins.nvim-tree")
require("nyto.plugins.lualine")
require("nyto.plugins.telescope")
require("nyto.plugins.nvim-cmp")
require("nyto.plugins.lsp.mason")
require("nyto.plugins.lsp.lspsaga")
require("nyto.plugins.lsp.lspconfig")
require("nyto.plugins.lsp.null-ls")
require("nyto.plugins.autopairs")
require("nyto.plugins.treesitter")
require("nyto.plugins.gitsigns")
